export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_FORGOT_PASSWORD_MESSAGE = "SET_FORGOT_PASSWORD_MESSAGE";
export const CLEAR_FORGOT_PASSWORD_MESSAGE = "CLEAR_FORGOT_PASSWORD_MESSAGE";

export const SET_CHANGE_PASSWORD_MESSAGE = "SET_CHANGE_PASSWORD_MESSAGE";
export const CLEAR_CHANGE_PASSWORD_MESSAGE = "CLEAR_CHANGE_PASSWORD_MESSAGE";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const SET_USERS = "SET_USERS";
export const FETCHING_USERS = "FETCHING_USERS";
export const SET_ROLE_OPTIONS = "SET_ROLE_OPTIONS"
export const SET_USER = "SET_USER";

export const ROLE_SUCCESS = "ROLE_SUCCESS";
export const ROLE_FAIL = "ROLE_FAIL";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAIL = "GET_ROLES_FAIL";
export const SET_ROLES = "SET_ROLES";
export const FETCHING_ROLES = "FETCHING_ROLES";
export const SET_ROLE = "SET_ROLE";

export const SET_REPORTS = "SET_REPORTS";
export const FETCHING_REPORTS = "FETCHING_REPORTS";